---

- name: Make passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Backup the current ssh config
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.bak  # BACKUP
    follow: yes



